// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Application.DTO
{

    // Matches
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Match
    {
        public int Id { get; set; } // ID (Primary key)
        public System.DateTime Date { get; set; } // Date
        public string Field { get; set; } // Field (length: 10)
        public string City { get; set; } // City (length: 50)
        public string State { get; set; } // State (length: 10)
        public int TeamA { get; set; } // TeamA
        public int TeamB { get; set; } // TeamB

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Score> Scores { get; set; } // Many to many mapping

        // Foreign keys
        public virtual Team Team_TeamA { get; set; } // FK_Matches_TeamsA
        public virtual Team Team_TeamB { get; set; } // FK_Matches_TeamsB

        public Match()
        {
            Scores = new System.Collections.Generic.List<Score>();
        }
    }

}
// </auto-generated>
