// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Application.DTO
{

    // Scores
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Score
    {
        public int Id { get; set; } // ID
        public int TeamId { get; set; } // TeamID
        public int MatchId { get; set; } // MatchID
        public int Score_ { get; set; } // Score

        // Foreign keys
        public virtual Match Match { get; set; } // FK_Scores_Matches
        public virtual Team Team { get; set; } // FK_Scores_Teams
    }

}
// </auto-generated>
