// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Application.DTO
{

    // Teams
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Team
    {
        public int Id { get; set; } // ID (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string State { get; set; } // State (length: 50)
        public string Logo { get; set; } // Logo (length: 50)
        public string Shorts { get; set; } // Shorts (length: 10)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Match> TeamA { get; set; } // Matches.FK_Matches_TeamsA
        public virtual System.Collections.Generic.ICollection<Match> TeamB { get; set; } // Matches.FK_Matches_TeamsB
        public virtual System.Collections.Generic.ICollection<Score> Scores { get; set; } // Many to many mapping

        public Team()
        {
            TeamA = new System.Collections.Generic.List<Match>();
            TeamB = new System.Collections.Generic.List<Match>();
            Scores = new System.Collections.Generic.List<Score>();
        }
    }

}
// </auto-generated>
