// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace EFProvider
{
    using Application.DTO;

    // Teams
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class TeamConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Team>
    {
        public TeamConfiguration()
            : this("dbo")
        {
        }

        public TeamConfiguration(string schema)
        {
            ToTable("Teams", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.State).HasColumnName(@"State").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Logo).HasColumnName(@"Logo").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Shorts).HasColumnName(@"Shorts").IsOptional().IsFixedLength().HasColumnType("nchar").HasMaxLength(10);
        }
    }

}
// </auto-generated>
